;;;; dsmr-mcp.asd

;; Tell ASDF that eclector.parse-result et al. live in :eclector.
(asdf:register-system-packages "eclector"
                               '(:eclector.parse-result
                                 :eclector.reader
                                 :eclector.base))

(asdf:defsystem "dsmr-mcp"
  :class :package-inferred-system
  :description
  "DeepSky Systems Model-Context-Protocol server for Common Lisp: an
attached-image-first MCP exposing the verbs an agent needs to write
and debug Lisp inside a live development image, with hermetic
file-based ICP as a fallback for crash isolation and parallel workers."
  :author "Brian O'Reilly <fade@deepsky.com>"
  :license "AGPL-3.0-or-later"
  :version "0.1.0"
  :depends-on ("alexandria"
               "cl-ppcre"
               "com.inuoe.jzon"
               "closer-mop"
               "ubiquitous"
               "usocket"
               "bordeaux-threads"
               "eclector"
               "hunchentoot"
               "flexi-streams"
               "log4cl"
               "slynk-client"
               "pzmq"
               "dsmr-mcp/src/main"
               "dsmr-mcp/src/wire-strings"
               "dsmr-mcp/src/protocol"
               "dsmr-mcp/src/elicitation"
               "dsmr-mcp/src/attach/registry"
               "dsmr-mcp/src/attach/dispatch"
               "dsmr-mcp/src/hermetic/worker-client"
               "dsmr-mcp/src/hermetic/worker/server"
               "dsmr-mcp/src/hermetic/worker/registry"
               "dsmr-mcp/src/hermetic/worker/inspect"
               "dsmr-mcp/src/hermetic/worker/handlers"
               "dsmr-mcp/src/hermetic/worker/main"
               "dsmr-mcp/src/hermetic/pool"
               "dsmr-mcp/src/orphan"
               "dsmr-mcp/src/transport/dispatch-pool"
               "dsmr-mcp/src/attach/cancel"
               "dsmr-mcp/src/hermetic/dispatch"
               "dsmr-mcp/src/project-root"
               "dsmr-mcp/src/fs"
               "dsmr-mcp/src/package-context"
               "dsmr-mcp/src/cst"
               "dsmr-mcp/src/lisp-read-file"
               "dsmr-mcp/src/parinfer"
               "dsmr-mcp/src/lisp-edit-form-core"
               "dsmr-mcp/src/lisp-edit-form"
               "dsmr-mcp/src/lisp-patch-form"
               "dsmr-mcp/src/lisp-edit-comment-core"
               "dsmr-mcp/src/lisp-edit-comment"
               "dsmr-mcp/src/validate"
               "dsmr-mcp/src/clgrep"
               "dsmr-mcp/src/tools/lisp-check-parens"
               "dsmr-mcp/src/tools/lisp-read-file"
               "dsmr-mcp/src/tools/lisp-edit-form"
               "dsmr-mcp/src/tools/lisp-patch-form"
               "dsmr-mcp/src/tools/lisp-edit-comment"
               "dsmr-mcp/src/tools/fs-set-project-root"
               "dsmr-mcp/src/tools/fs-get-project-info"
               "dsmr-mcp/src/tools/fs-read-file"
               "dsmr-mcp/src/tools/fs-write-file"
               "dsmr-mcp/src/tools/fs-list-directory"
               "dsmr-mcp/src/tools/clgrep-search"
               "dsmr-mcp/src/tools/inspect-object"
               "dsmr-mcp/src/code-core"
               "dsmr-mcp/src/system-loader-core"
               "dsmr-mcp/src/test-runner-core"
               "dsmr-mcp/src/tools/code-find"
               "dsmr-mcp/src/tools/code-describe"
               "dsmr-mcp/src/tools/code-find-references"
               "dsmr-mcp/src/tools/load-system"
               "dsmr-mcp/src/tools/run-tests"
               "dsmr-mcp/src/tools/inspect-thread"
               "dsmr-mcp/src/tools/inspect-restart"
               "dsmr-mcp/src/tools/inspect-condition"
               "dsmr-mcp/src/tools/pool-status"
               "dsmr-mcp/src/tools/pool-kill-worker"
               "dsmr-mcp/src/reset"
               "dsmr-mcp/src/tools/reset-local"
               "dsmr-mcp/src/tools/reset-peer"
               "dsmr-mcp/src/tools/restart-process"
               "dsmr-mcp/src/notify"
               "dsmr-mcp/src/transport/tcp"
               "dsmr-mcp/src/transport/http"
               "dsmr-mcp/src/lsp/client"
               "dsmr-mcp/src/lsp/document"
               "dsmr-mcp/src/lsp/bridge"
               "dsmr-mcp/src/tools/lsp-completions"
               "dsmr-mcp/src/tools/lsp-hover"
               "dsmr-mcp/src/tools/lsp-diagnostics"
               "dsmr-mcp/src/tools/lsp-code-actions"
               "dsmr-mcp/src/attach/probe"
               "dsmr-mcp/src/slynk-port"
               "dsmr-mcp/src/envrc-template"
               "dsmr-mcp/src/git"
               "dsmr-mcp/src/repo-classify"
               "dsmr-mcp/src/project-shape"
               "dsmr-mcp/src/project-scaffold-templates"
               "dsmr-mcp/src/project-shape-catalog"
               "dsmr-mcp/src/project-scaffold-core"
               "dsmr-mcp/src/project-scaffold"
               "dsmr-mcp/src/tools/project-scaffold"
               "dsmr-mcp/src/clhs"
               "dsmr-mcp/src/tools/clhs-lookup"
               "dsmr-mcp/src/install/config"
               "dsmr-mcp/src/install/defaults"
               "dsmr-mcp/src/install/claude"
               "dsmr-mcp/src/install/hooks"
               "dsmr-mcp/src/install"
               "dsmr-mcp/src/envrc-vars"
               "dsmr-mcp/src/envrc-init"
               "dsmr-mcp/src/bus/wal"
               "dsmr-mcp/src/bus/cursor"
               "dsmr-mcp/src/bus/election"
               "dsmr-mcp/src/bus/wakeup"
               "dsmr-mcp/src/bus/archive"
               "dsmr-mcp/src/bus/zmq"
               "dsmr-mcp/src/bus/selector"
               "dsmr-mcp/src/bus/roster"
               "dsmr-mcp/src/bus/broker"
               "dsmr-mcp/src/bus/envelope"
               "dsmr-mcp/src/bus/heartbeat"
               "dsmr-mcp/src/bus/bus"
               "dsmr-mcp/src/bus/agent"
               "dsmr-mcp/src/tools/bus-helpers"
               "dsmr-mcp/src/tools/bus-publish"
               "dsmr-mcp/src/tools/bus-receive"
               "dsmr-mcp/src/tools/bus-status"
               "dsmr-mcp/src/tools/bus-roster"
               "dsmr-mcp/src/tools/bus-leave"
               "dsmr-mcp/src/bus-listener")
  :in-order-to ((test-op (test-op "dsmr-mcp/tests"))))

(asdf:defsystem "dsmr-mcp/tests"
  :class :package-inferred-system
  :description "Test suite for dsmr-mcp."
  :depends-on ("parachute"
               "slynk"
               "dsmr-mcp"
               "dsmr-mcp/tests/smoke-test"
               "dsmr-mcp/tests/support/json-asserts"
               "dsmr-mcp/tests/support/parachute-report"
               "dsmr-mcp/tests/support/slynk-fixture"
               "dsmr-mcp/tests/support/bounded-eval"
               "dsmr-mcp/tests/support/portability-guard"
               "dsmr-mcp/tests/support/env-fixture"
               "dsmr-mcp/tests/state/session-test"
               "dsmr-mcp/tests/protocol/handshake-test"
               "dsmr-mcp/tests/protocol/version-negotiation-test"
               "dsmr-mcp/tests/protocol/strict-initialize-test"
               "dsmr-mcp/tests/protocol/tools-list-test"
               "dsmr-mcp/tests/protocol/tools-doc-parity-test"
               "dsmr-mcp/tests/protocol/tools-call-test"
               "dsmr-mcp/tests/protocol/prompts-test"
               "dsmr-mcp/tests/protocol/argument-validation-test"
               "dsmr-mcp/tests/protocol/wire-string-normalization-test"
               "dsmr-mcp/tests/transport/stdio-test"
               "dsmr-mcp/tests/transport/concurrent-dispatch-test"
               "dsmr-mcp/tests/orphan-test"
               "dsmr-mcp/tests/run-test"
               "dsmr-mcp/tests/attach/repl-eval-attach-test"
               "dsmr-mcp/tests/attach/registry-test"
               "dsmr-mcp/tests/log/log-test"
               "dsmr-mcp/tests/dispatch/mode-router-test"
               "dsmr-mcp/tests/dispatch/result-content-guard-test"
               "dsmr-mcp/tests/hermetic/inspect-test"
               "dsmr-mcp/tests/attach/inspect-test"
               "dsmr-mcp/tests/attach/inspect-thread-test"
               "dsmr-mcp/tests/attach/inspect-restart-test"
               "dsmr-mcp/tests/attach/inspect-condition-test"
               "dsmr-mcp/tests/support/fs-fixture"
               "dsmr-mcp/tests/support/git-fixture"
               "dsmr-mcp/tests/git/git-primitives-test"
               "dsmr-mcp/tests/repo/repo-classify-test"
               "dsmr-mcp/tests/fs/sandbox-test"
               "dsmr-mcp/tests/fs/symlink-escape-test"
               "dsmr-mcp/tests/fs/project-root-test"
               "dsmr-mcp/tests/fs/fs-verbs-test"
               "dsmr-mcp/tests/fs/lisp-read-file-test"
               "dsmr-mcp/tests/lisp-edit-form-test"
               "dsmr-mcp/tests/lisp-patch-form-test"
               "dsmr-mcp/tests/lisp-edit-comment-test"
               "dsmr-mcp/tests/validate-test"
               "dsmr-mcp/tests/clgrep-test"
               "dsmr-mcp/tests/code-intelligence/code-core-test"
               "dsmr-mcp/tests/code-intelligence/code-find-test"
               "dsmr-mcp/tests/code-intelligence/code-describe-test"
               "dsmr-mcp/tests/code-intelligence/code-find-refs-test"
               "dsmr-mcp/tests/code-intelligence/load-system-test"
               "dsmr-mcp/tests/code-intelligence/run-tests-test"
               "dsmr-mcp/tests/notify/notify-test"
               "dsmr-mcp/tests/attach/probe-test"
               "dsmr-mcp/tests/attach/call-lock-test"
               "dsmr-mcp/tests/transport/tcp-test"
               "dsmr-mcp/tests/transport/http-test"
               "dsmr-mcp/tests/transport/transport-parity-test"
               "dsmr-mcp/tests/support/lsp-mock"
               "dsmr-mcp/tests/lsp/client-test"
               "dsmr-mcp/tests/lsp/document-test"
               "dsmr-mcp/tests/lsp/bridge-test"
               "dsmr-mcp/tests/shape/project-shape-test"
               "dsmr-mcp/tests/scaffold/project-scaffold-test"
               "dsmr-mcp/tests/clhs/clhs-lookup-test"
               "dsmr-mcp/tests/install/config-test"
               "dsmr-mcp/tests/envrc-template/envrc-template-test"
               "dsmr-mcp/tests/envrc-template/envrc-vars-test"
               "dsmr-mcp/tests/scaffold/project-scaffold-envrc-test"
               "dsmr-mcp/tests/elicitation/elicitation-test"
               "dsmr-mcp/tests/elicitation/launch-trigger-test"
               "dsmr-mcp/tests/elicitation/envrc-consent-schema-test"
               "dsmr-mcp/tests/install/defaults-test"
               "dsmr-mcp/tests/install/install-binary-test"
               "dsmr-mcp/tests/install/hooks-test"
               "dsmr-mcp/tests/install/install-entry-hook-test"
               "dsmr-mcp/tests/slynk-port-test"
               "dsmr-mcp/tests/bus/wal-test"
               "dsmr-mcp/tests/bus/cursor-test"
               "dsmr-mcp/tests/bus/cursor-reap-test"
               "dsmr-mcp/tests/bus/selector-test"
               "dsmr-mcp/tests/bus/roster-test"
               "dsmr-mcp/tests/bus/envelope-test"
               "dsmr-mcp/tests/bus/election-test"
               "dsmr-mcp/tests/bus/wakeup-test"
               "dsmr-mcp/tests/bus/watch-test"
               "dsmr-mcp/tests/bus/watch-leaf-isolation-test"
               "dsmr-mcp/tests/bus/archive-test"
               "dsmr-mcp/tests/bus/zmq-test"
               "dsmr-mcp/tests/bus/flow-test"
               "dsmr-mcp/tests/bus/agent-test"
               "dsmr-mcp/tests/bus/self-echo-test"
               "dsmr-mcp/tests/tools/bus-identity-test"
               "dsmr-mcp/tests/tools/bus-receive-test"
               "dsmr-mcp/tests/tools/bus-roster-test"
               "dsmr-mcp/tests/tools/bus-addressing-test"
               "dsmr-mcp/tests/tools/reset-local-test"
               "dsmr-mcp/tests/tools/reset-peer-test"
               "dsmr-mcp/tests/tools/restart-process-test"
               "dsmr-mcp/tests/bus-listener-test"
               "dsmr-mcp/tests/report/axis-summary-test")
  :perform (test-op (o c)
                    (declare (ignore o))
                    (let* ((test-package-names
                            (remove-if-not
                             (lambda (dep)
                               (and (stringp dep)
                                    (uiop:string-prefix-p "dsmr-mcp/tests/" dep)))
                             (asdf:system-depends-on c)))
                           (any-failed nil))
                      (dolist (name test-package-names)
                        (let* ((package (or (find-package (string-upcase name))
                                            (error "Test package ~S not loaded." name)))
                               (result (uiop:symbol-call :parachute :test package)))
                          (when (uiop:symbol-call :parachute :results-with-status
                                                  :failed result)
                            (setf any-failed t))))
                      (when any-failed
                        (error "dsmr-mcp/tests: one or more parachute tests failed.")))))

;; Slow cross-process integration tests, kept OUT of the fast dsmr-mcp/tests
;; umbrella so the inner-loop suite stays quick. Each leaf here spawns a real
;; dsmr-mcp server subprocess (~10-12s/scenario) and skips cleanly when the
;; environment cannot spawn one. Run explicitly: (asdf:test-system "dsmr-mcp/tests/integration").

(asdf:defsystem "dsmr-mcp/tests/integration"
  :class :package-inferred-system
  :description "Slow cross-process integration tests for dsmr-mcp."
  :depends-on ("parachute"
               "com.inuoe.jzon"
               "slynk"
               "dsmr-mcp"
               "dsmr-mcp/tests/integration/stdio-elicitation-test"
               "dsmr-mcp/tests/integration/transport/stdio-integration-test"
               "dsmr-mcp/tests/integration/transport/bridge-test"
               "dsmr-mcp/tests/integration/attach/wire-cross-process-test"
               "dsmr-mcp/tests/integration/attach/run-tests-cross-process-test"
               "dsmr-mcp/tests/integration/attach/error-context-guard-test"
               "dsmr-mcp/tests/integration/attach/cancel-test"
               "dsmr-mcp/tests/integration/hermetic/cancel-test"
               "dsmr-mcp/tests/integration/hermetic/worker-spawn-test"
               "dsmr-mcp/tests/integration/hermetic/repl-eval-parity-test"
               "dsmr-mcp/tests/integration/hermetic/circuit-breaker-test"
               "dsmr-mcp/tests/integration/hermetic/pool-affinity-test"
               "dsmr-mcp/tests/integration/bus/failover-test"
               "dsmr-mcp/tests/integration/bus/segmentation-test"
               "dsmr-mcp/tests/integration/bus/watch-integration-test"
               "dsmr-mcp/tests/integration/scripts/launcher-supervise-test")
  :perform (test-op (o c)
                    (declare (ignore o))
                    (let* ((test-package-names
                            (remove-if-not
                             (lambda (dep)
                               (and (stringp dep)
                                    (uiop:string-prefix-p "dsmr-mcp/tests/integration/" dep)))
                             (asdf:system-depends-on c)))
                           (any-failed nil))
                      (dolist (name test-package-names)
                        (let* ((package (or (find-package (string-upcase name))
                                            (error "Test package ~S not loaded." name)))
                               (result (uiop:symbol-call :parachute :test package)))
                          (when (uiop:symbol-call :parachute :results-with-status
                                                  :failed result)
                            (setf any-failed t))))
                      (when any-failed
                        (error "dsmr-mcp/tests/integration: one or more parachute tests failed.")))))
